#!/usr/bin/env python3
"""Generate a Windows resource script (.rc) that embeds a game's assets
into the .exe as RCDATA resources.

The runtime (graphics.c, open_asset) looks assets up by their path relative
to the assets directory, e.g. "grass.png" or "fonts/ChillRoundGothic_Heavy.ttf".
The same relative name (forward slashes) becomes the resource name, so the
Windows build is fully self-contained: no loose PNG/TTF files next to
Game.exe in the release package.

Usage: embed_assets.py <assets-dir> <output.rc>
"""
from __future__ import annotations

import os
import sys
from pathlib import Path


def rc_quote_path(p: str) -> str:
    # Resource scripts are C-like: escape backslashes and double quotes.
    return p.replace("\\", "\\\\").replace('"', '\\"')


def generate(source: Path, destination: Path) -> list[str]:
    source = source.resolve()
    if not source.is_dir():
        raise ValueError(f"asset directory not found: {source}")
    lines = [
        "// Auto-generated by embed_assets.py — do not edit.",
        "// RCDATA — встроенный тип rc.exe, #include <windows.h> не нужен.",
        "",
    ]
    names: list[str] = []
    for path in sorted(source.rglob("*")):
        if not path.is_file() or path.name == ".gitkeep":
            continue
        # Имя ресурса — путь относительно assets с прямыми слэшами (так его
        # запрашивает код), а вот файл для rc.exe нужен АБСОЛЮТНЫМ путём с
        # каноническими обратными слэшами: rc.exe ищет относительные пути от
        # своего рабочего каталога (в MSBuild это промежуточная папка).
        rel = path.relative_to(source).as_posix()
        disk = os.path.normpath(str(path))  # абсолютный, \ на Windows
        lines.append(f'"{rc_quote_path(rel)}" RCDATA "{rc_quote_path(disk)}"')
        names.append(rel)
    lines.append("")
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text("\n".join(lines), encoding="utf-8")
    return names


def main(argv: list[str] | None = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    source = Path(args[0]) if len(args) >= 1 else Path("game/assets")
    destination = Path(args[1]) if len(args) >= 2 else Path("embedded_assets.rc")
    try:
        names = generate(source, destination)
    except (OSError, ValueError) as error:
        print(f"Error: {error}", file=sys.stderr)
        return 1
    print(f"Embedded {len(names)} asset(s) into {destination}")
    for name in names:
        print(f"  {name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
